ext {
    apply from: "$rootDir/api/manifest.gradle"

    gitCommitId = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
    gitCommitCount = Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())

    moduleLibraryName = "sui"
    moduleMinRiruApiVersion = 25
    moduleMinRiruVersionName = "v25.0.0"
    moduleRiruApiVersion = 25

    riruModuleId = "riru-sui"
    zygiskModuleId = "zygisk-sui"

    moduleName = "Zygisk - sui ."
    moduleAuthor = "khalifa ."
    moduleDescription = "Modern superuser interface implementation."
    moduleVersionMajor = 18
    moduleVersionMinor = 9
    moduleVersionPatch = 14
    moduleVersion = "v${moduleVersionMajor}.${moduleVersionMinor}.${moduleVersionPatch}"
    moduleVersionCode = gitCommitCount

}
